server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://1.117.51.92:3306/forum?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: outer
    password: XMGL601!fdu,

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头